version: '3.1'
services:
  frontend:
    container_name: frontend
    image: node
    user: node
    working_dir: /home/frontend
    volumes:
      - ./frontend:/home/frontend
    environment:
      - NODE_ENV=production
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
    - "3000:3000"
    restart: always
    command: "npm start"
