version: '3.1'
services:
  backend:
    container_name: backend
    image: node
    user: node
    working_dir: /home/backend
    volumes:
      - ./backend:/home/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - URL_DB_CONNECTION=${URL_DB_CONNECTION} #mongodb://host.docker.internal/bookstore-production
    ports:
      - "5000:5000"
    restart: always
    command: "npm start"
